name: update-releases
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '0 17 * * MON' # 5PM Monday UTC (10AM Monday PST) - Set to 2hrs after react-native-windows publish starts
    - cron:  '0 22 * * *' # 10PM UTC (3PM PST) Everyday
jobs:
  check-bats-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all branches etc
          ref: 'main'
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      # Clean up some unneeded disk hogs
      # - run: |
      #     $path = "$Env:Programfiles"
      #     $colItems = Get-ChildItem $path | Where-Object {$_.PSIsContainer -eq $true} | Sort-Object
      #     foreach ($i in $colItems)
      #     {
      #         $subFolderItems = Get-ChildItem $i.FullName -recurse -force | Where-Object {$_.PSIsContainer -eq $false} | Measure-Object -property Length -sum | Select-Object Sum
      #         $i.FullName + " -- " + "{0:N2}" -f ($subFolderItems.sum / 1MB) + " MB"
      #     }
      - run: Remove-Item "$Env:Programfiles\Azure Cosmos DB Emulator" -Recurse -Force -ErrorAction SilentlyContinue -ErrorVariable err
      - run: Write-Host $err
      - run: Remove-Item "$Env:Programfiles\LLVM" -Recurse -Force -ErrorAction SilentlyContinue -ErrorVariable err
      - run: Write-Host $err
      # - run: |
      #     $path = "$Env:Programfiles"
      #     $colItems = Get-ChildItem $path | Where-Object {$_.PSIsContainer -eq $true} | Sort-Object
      #     foreach ($i in $colItems)
      #     {
      #         $subFolderItems = Get-ChildItem $i.FullName -recurse -force | Where-Object {$_.PSIsContainer -eq $false} | Measure-Object -property Length -sum | Select-Object Sum
      #         $i.FullName + " -- " + "{0:N2}" -f ($subFolderItems.sum / 1MB) + " MB"
      #     }
      - run: git config --global user.email "30809111+acoates-ms@users.noreply.github.com"
      - run: git config --global user.name "Andrew Coates"
      - run: git fetch origin main
      - run: git checkout main
      - run: npm install semver
      - run: node generate-all.js onlyOne
      - run: git add RELEASES
      - run: ${{ "& {git commit -m "Update RELEASES"}" }}
      - run: git push

  check-bats-mac:
    runs-on: windows-latest
    needs: check-bats-windows
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all branches etc
          ref: 'main'
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      # Clean up some unneeded disk hogs
      - run: Remove-Item "$Env:Programfiles\Azure Cosmos DB Emulator" -Recurse -Force -ErrorAction SilentlyContinue -ErrorVariable err
      - run: Write-Host $err
      - run: Remove-Item "$Env:Programfiles\LLVM" -Recurse -Force -ErrorAction SilentlyContinue -ErrorVariable err
      - run: Write-Host $err
      - run: git config --global user.email "30809111+acoates-ms@users.noreply.github.com"
      - run: git config --global user.name "Andrew Coates"
      - run: git fetch origin main
      - run: git checkout main
      - run: npm install semver
      - run: node generate-all-mac.js onlyOne
      - run: git add RELEASES_MAC
      - run: ${{ "& {git commit -m "Update RELEASES_MAC"}" }}
      - run: git push
